<?php
/** @var \Roweb\Authors\Block\Template $block */
?>
<form class="" action="<?php echo $block->getBaseUrl() . 'authors/index/save'; ?>" id="roweb-authors-form" method="post"
    enctype='multipart/form-data' data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend">
            <span>
                <a href="<?php echo $block->getBaseUrl() . 'authors/index/list'; ?>">(Visit List Page)</a>
            </span>
        </legend><br>
    </fieldset>
</form>