<?php
/** @var \Roweb\Authors\Block\Template $block */
?>

<?php
$singleData = $block->getSingleData();
?>
<div>
    <h3>Author</h3>
    <p>
        <?php echo $singleData->getName(); ?>
    </p>
</div>
<div>
    <h3>Description</h3>
    <p>
        <?php echo $singleData->getDescription(); ?>
    </p>
</div>
<div>
    <h3>Image</h3>
    <?php if ($singleData->getImage()): ?>
        <img width="400" height="300" src="<?php echo $block->getBaseUrl() . 'media/' . $singleData->getImage(); ?>">
    <?php else: ?>
        <p>No Image</p>
    <?php endif; ?>
</div>